stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: osrf/ros:rolling-desktop
  before_script:
    - git clone -b rolling https://gitlab.com/ApexAI/apex_test_tools # Fixme
    - apt-get update
    - rosdep update
    - rosdep install --from apex_test_tools --ignore-src -y
    - '
      colcon build
          --install-base /opt/ros/rolling
          --merge-install
          --cmake-args
              -DCMAKE_BUILD_TYPE=Release
          --base-path apex_test_tools
      '
    - rm -r build log apex_test_tools
  script:
    - rosdep install --from apex_containers --ignore-src -y --skip-keys "apex_test_tools" # Fixme
    - mkdir -p /opt/apex_containers
    - '
      colcon build
          --install-base /opt/apex_containers
          --merge-install
          --cmake-args
            -DCMAKE_BUILD_TYPE=Release
          --base-path apex_containers
      '
    - cp LICENSE /opt/apex_containers
    - tar cfz opt.tar.gz /opt/apex_containers
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - log
      - build
      - opt.tar.gz

test:
  stage: test
  image: osrf/ros:rolling-desktop
  dependencies:
    - build
  before_script:
    - apt-get update
    - git clone -b rolling https://gitlab.com/ApexAI/apex_test_tools # Fixme
    - rosdep update
    - rosdep install --from apex_test_tools --ignore-src -y
    - '
      colcon build
          --install-base /opt/ros/rolling
          --merge-install
          --cmake-args
              -DCMAKE_BUILD_TYPE=Release
          --base-path apex_test_tools
      '
    - rm -r apex_test_tools
  script:
    - tar xf opt.tar.gz -C /
    - '
      colcon test
          --install-base /opt/apex_containers
          --merge-install
          --base-path apex_containers
          --packages-select apex_containers
      '
    - 'colcon test-result --verbose'
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - log

volume:
  stage: deploy
  image: docker
  services:
    - docker:dind
  dependencies:
    - build
  before_script:
    - ''
  script:
    - 'echo -e "*\n!opt.tar.gz" > .dockerignore'
    - |
      cat >Dockerfile <<EOF
      FROM alpine
      ADD opt.tar.gz /
      VOLUME /opt/apex_containers
      CMD ["/bin/sh", "-c", "trap 'exit 147' TERM; tail -f /dev/null & wait ${!}"]
      EOF
    - '
      docker build
          --label ade_image_commit_sha="$CI_COMMIT_SHA"
          --label ade_image_commit_tag="$CI_COMMIT_TAG"
          -t image .
      '
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker tag image $CI_REGISTRY_IMAGE:commit-$CI_COMMIT_SHA
    - docker tag image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:commit-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
